title = "the script for gpt inference"

# [Model]
model_path = "Output/train_gpt/Checkpoint/model-1-epoch-1-step-63046"   # !!!

max_output_seq_length = 25
seed = 42

n_gpu = 1
top_p = 0.9
temperature = 0.0
test_file_path = "../Dataset/msmarco_cs/cs/preprocessed/gpt_inference_input.json"


# [Output]
output_file_path = "../Dataset/msmarco_cs/cs/preprocessed/output.json"
