title = "test with bm25"

# [Input]
index_dir_path = "../Passage_Collection/qrecc/indexes"
input_query_path = "../Dataset/qrecc/preprocessed/test.json"
query_type = "raw"
top_k = 100
bm25_k1 = 0.82   # 0.82 for qrecc, 0.9 for topiocqa
bm25_b = 0.68    # 0.68 for qrecc, 0.4 for topiocqa
rel_threshold = 1


# [Output]
output_dir_path = "./Output/test_bm25/qrecc/concat_with_last_passage"
gold_qrel_file_path = "../Dataset/qrecc/preprocessed/qrecc_qrel.tsv"
