title = "the test script to test a model on AOL benchmarks"

# [Model]
query_encoder_checkpoint = "../COTED/checkpoints/ad-hoc-ance-msmarco"   # !!!
pretrained_passage_encoder = "../COTED/checkpoints/ad-hoc-ance-msmarco"

max_concat_length = 128
max_query_length = 64
max_doc_length = 128
seed = 42

# [Model]
model_type = "ANCE"
n_gpu = 1

# [Test]
per_gpu_eval_batch_size = 8
use_data_percent = 0.1
disable_tqdm = false
test_type = "baseline_raw"


test_file_path = "../Dataset/aol/preprocessed/test.json"
gold_qrel_file_path = ""
enable_last_repsone = true 
