title = "this is specific for training CQE on msmarco"

# [Model]
model_type = "ANCE"
pretrained_query_encoder = "../COTED/checkpoints/ad-hoc-ance-msmarco"
pretrained_passage_encoder = "../COTED/checkpoints/ad-hoc-ance-msmarco"

max_concat_length = 512
max_query_length = 64
max_doc_length = 384

# [Train]
train_type = "ranking" # kd or ranking
num_train_epochs = 5   # !!
per_gpu_train_batch_size = 2    # !!
n_gpu = 1   # !!
disable_tqdm = false    # !!


save_steps = -1   # !! int (steps) or float (ratio of a epoch)
print_steps =  0.001  # print the loss
learning_rate = 1e-5
weight_decay = 0.0
adam_epsilon = 1e-8
num_warmup_steps = 0
max_grad_norm = 1.0

enable_last_repsone = true
special_assemble_conv_query = true  # !!
response_type = "passage"
seed = 42

use_data_percent = 0.01    # !!


# [Input Data]
train_file_path = "../Dataset/msmarco_cs/self_learn/new_self_learn_weak_data.json"

# [Output]
overwrite_output_dir = true
log_dir_path = "./Output/pretrain_msmarco/Log"
model_output_path = "./Output/pretrain_msmarco/Checkpoint"



