title = "a basic config for train gpt model."

# [Model]
model_path = "gpt2-medium"

max_seq_length = 50

# [Train]
num_train_epochs = 4   # !!
per_gpu_train_batch_size = 2    # !!
n_gpu = 1   # !!
disable_tqdm = false    # !!


save_steps = 1.0   # !! int (steps) or float (ratio of a epoch)
print_steps =  0.001  # print the loss
learning_rate = 5e-5
weight_decay = 0.0
adam_epsilon = 1e-8
num_warmup_steps = 0
max_grad_norm = 1.0


seed = 42
use_data_percent = 1.0    # !!


# [Input Data]
train_file_path = "../Dataset/msmarco_cs/session2conv/train.json"

# [Output]
overwrite_output_dir = true
log_dir_path = "./Output/train_gpt/Log"
model_output_path = "./Output/train_gpt/Checkpoint"



